notifications:
  email: false
  
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install: pip3 install -r requirements.txt
  
script:
  - python checkxss.py -h
env: CODECOV_TOKEN="a860674a-3287-4722-b846-63526ca3ab6d"

CODECOV_TOKEN="a860674a-3287-4722-b846-63526ca3ab6d"
